import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>GoBorneo - Kalimantan Tourism Information</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.instagram.com/goborneo.id">goborneo.id</a>
        </h1>
        <h3>Kalimantan Tourism Information</h3>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}
